"use client";
import {useState} from "react";
import Link from "next/link";
const API=process.env.NEXT_PUBLIC_API_URL||"";
export default function PartnerDashboard(){
 const [partnerId,setPartnerId]=useState(""); const [partner,setPartner]=useState<any>(null); const [products,setProducts]=useState<any[]>([]); const [orders,setOrders]=useState<any[]>([]); const [message,setMessage]=useState("");
 const [form,setForm]=useState({name:"",category:"",description:"",price:"",imageUrl:""});
 async function load(){try{const p=await fetch(API+"/api/portal/partners").then(r=>r.json());const found=(p.partners||[]).find((x:any)=>String(x.id)===partnerId);if(!found){setMessage("Partner account not found.");return}setPartner(found);const list=await fetch(API+"/api/marketplace/partner-products").then(r=>r.json());setProducts((list.products||[]).filter((x:any)=>String(x.partner_id)===partnerId));setMessage(found.status==="approved"?"Welcome to your Partner Dashboard.":"Your application is still "+found.status+".");}catch{setMessage("Unable to connect to LUMIA backend.")}}
 async function addProduct(e:any){e.preventDefault();if(!partner||partner.status!=="approved")return;const r=await fetch(API+"/api/portal/partners/"+partner.id+"/products",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,price:Number(form.price)||0})});if(r.ok){setForm({name:"",category:"",description:"",price:"",imageUrl:""});setMessage("Product added successfully.");load()}else setMessage("Unable to add product.")}
 return <main className="partnerDash"><header className="partnerDashHeader"><Link href="/marketplace" className="marketBrand"><b>L</b> LUMIA <span>PARTNER</span></Link><Link href="/marketplace">← Back to Marketplace</Link></header>
 {!partner?<section className="partnerLogin"><p className="eyebrow">PARTNER ACCESS</p><h1>Manage your LUMIA Partner business</h1><p>Enter your Partner ID after your application has been reviewed by the LUMIA Team.</p><input value={partnerId} onChange={e=>setPartnerId(e.target.value)} placeholder="Partner ID"/><button onClick={load}>Open Dashboard</button>{message&&<p>{message}</p>}</section>:
 <><section className="partnerHeroDash"><div><p className="eyebrow">WELCOME BACK</p><h1>{partner.business_name}</h1><p>{partner.location||"LUMIA Marketplace Partner"} · Status: <b>{partner.status}</b></p></div><div className="dashStats"><span><b>{products.length}</b> Products</span><span><b>{orders.length}</b> Orders</span><span><b>{partner.payment_status}</b> Payment</span></div></section>
 <section className="partnerContent"><div className="partnerBusinessCard"><h2>Business profile</h2><p><b>Owner:</b> {partner.owner_name}</p><p><b>WhatsApp:</b> {partner.whatsapp_number}</p><p><b>Category:</b> {partner.business_category||"—"}</p><p><b>Registration:</b> 40,000 RWF · MOMO PAY 935237</p><p>{message}</p></div>
 <div className="partnerProducts"><div className="dashTitle"><div><p className="eyebrow">CATALOG</p><h2>Your products</h2></div></div>{partner.status==="approved"?<form className="addProductForm" onSubmit={addProduct}><input required placeholder="Product name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required placeholder="Category" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><input required type="number" placeholder="Price (RWF)" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><input placeholder="Real product image URL" value={form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})}/><textarea placeholder="Product description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button>Add Product</button></form>:<div className="waitingBox">Your account must be approved by LUMIA Admin before you can publish products.</div>}
 <div className="partnerProductGrid">{products.map(x=><article key={x.id}><img src={x.image_url||"https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=80"} alt={x.name}/><h3>{x.name}</h3><p>{Number(x.price||0).toLocaleString()} RWF</p></article>)}</div></div></section>
 <section className="partnerOrders"><p className="eyebrow">CUSTOMER REQUESTS</p><h2>Orders & proof messages</h2><div className="waitingBox">Partner order notifications are delivered through the WhatsApp number registered on your Partner application. Orders will appear here as the backend dashboard endpoint is connected.</div></section></>}</main>