"use client";
import {useState} from "react";
import Link from "next/link";
const API=process.env.NEXT_PUBLIC_API_URL||"";
export default function PartnerDashboard(){
 const [login,setLogin]=useState({whatsappNumber:"",password:""});
 const [token,setToken]=useState(""); const [partner,setPartner]=useState<any>(null);
 const [products,setProducts]=useState<any[]>([]); const [orders,setOrders]=useState<any[]>([]);
 const [message,setMessage]=useState(""); const [form,setForm]=useState({name:"",category:"",description:"",price:"",imageUrl:""});
 async function loadDashboard(t:string){try{const headers={Authorization:"Bearer "+t};const [me,po,or]=await Promise.all([fetch(API+"/api/partner/me",{headers}).then(r=>r.json()),fetch(API+"/api/marketplace/partner-products").then(r=>r.json()),fetch(API+"/api/partner/orders",{headers}).then(r=>r.json())]);if(me.error)throw new Error(me.error);setPartner(me.partner);setProducts((po.products||[]).filter((x:any)=>x.partner_id===me.partner.id));setOrders(or.orders||[])}catch(e:any){setMessage(e.message||"Unable to load dashboard.")}}
 async function signIn(){try{const r=await fetch(API+"/api/partner/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(login)});const d=await r.json();if(!r.ok)throw new Error(d.error);setToken(d.token);setMessage("");await loadDashboard(d.token)}catch(e:any){setMessage(e.message||"Unable to sign in.")}}
 async function addProduct(e:any){e.preventDefault();try{const r=await fetch(API+"/api/partner/products",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({...form,price:Number(form.price)||0})});if(!r.ok)throw new Error("Unable to add product");setForm({name:"",category:"",description:"",price:"",imageUrl:""});setMessage("Product published successfully.");loadDashboard(token)}catch(e:any){setMessage(e.message)}}
 return <main className="partnerDash"><header className="partnerDashHeader"><Link href="/marketplace" className="marketBrand"><b>L</b> LUMIA <span>PARTNER</span></Link><Link href="/marketplace">← Back to Marketplace</Link></header>
 {!partner?<section className="partnerLogin"><p className="eyebrow">SECURE PARTNER ACCESS</p><h1>Manage your LUMIA Partner business</h1><p>Sign in with the WhatsApp number registered on your approved Partner account.</p><input value={login.whatsappNumber} onChange={e=>setLogin({...login,whatsappNumber:e.target.value})} placeholder="WhatsApp number" autoComplete="username"/><input type="password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} placeholder="Password" autoComplete="current-password"/><button onClick={signIn}>Sign in to Dashboard</button><p className="loginHelp">Your business must be approved by LUMIA Admin before you can activate and use your Partner account.</p>{message&&<p>{message}</p>}</section>:
 <><section className="partnerHeroDash"><div><p className="eyebrow">WELCOME BACK</p><h1>{partner.business_name}</h1><p>{partner.location||"LUMIA Marketplace Partner"} · Status: <b>{partner.status}</b></p></div><div className="dashStats"><span><b>{products.length}</b> Products</span><span><b>{orders.length}</b> Orders</span><span><b>{partner.payment_status}</b> Payment</span></div></section>
 <section className="partnerContent"><div className="partnerBusinessCard"><h2>Business profile</h2><p><b>Owner:</b> {partner.owner_name}</p><p><b>WhatsApp:</b> {partner.whatsapp_number}</p><p><b>Category:</b> {partner.business_category||"—"}</p><p><b>Registration:</b> 40,000 RWF · MOMO PAY 935237</p>{message&&<p>{message}</p>}</div>
 <div className="partnerProducts"><div className="dashTitle"><p className="eyebrow">CATALOG</p><h2>Your products</h2></div><form className="addProductForm" onSubmit={addProduct}><input required placeholder="Product name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required placeholder="Category" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><input required type="number" placeholder="Price (RWF)" value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/><input placeholder="Real product image URL" value={form.imageUrl} onChange={e=>setForm({...form,imageUrl:e.target.value})}/><textarea placeholder="Product description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button>Add Product</button></form><div className="partnerProductGrid">{products.map(x=><article key={x.id}><img src={x.image_url||"https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=80"} alt={x.name}/><h3>{x.name}</h3><p>{Number(x.price||0).toLocaleString()} RWF</p></article>)}</div></div></section>
 <section className="partnerOrders"><p className="eyebrow">CUSTOMER REQUESTS</p><h2>Orders & proof messages</h2><div className="ordersList">{orders.length?orders.map(o=><article className="partnerOrderCard" key={o.id}><span className="orderStatus">{o.status}</span><h3>{o.product_name}</h3><p><b>Customer:</b> {o.customer_name||"Customer"}</p><p><b>WhatsApp:</b> {o.customer_whatsapp||o.customer_phone}</p><p><b>Payment:</b> {o.payment_method} · {o.payment_status}</p><div className="proofBox">{o.proof_message}</div></article>):<div className="waitingBox">No customer orders yet. LUMIA AI will notify your registered WhatsApp number when a customer requests one of your products.</div>}</div></section></>}</main>}