"use client";

import { useEffect, useMemo, useState } from "react";
import { Search, ShoppingCart, Monitor, Smartphone, Shirt, Sun, Sofa, Wrench, HeartPulse, Baby, Globe, ArrowRight } from "lucide-react";

const API="https://lumia-whatsapp-agent.onrender.com";
const categories=[
["Clothing",Shirt],["Computers",Monitor],["Mobile Phones",Smartphone],["Solar",Sun],["Furniture",Sofa],["Equipment",Wrench],["Health & Care",HeartPulse],["Children",Baby],["Digital Services",Globe]
];

export default function Marketplace(){
 const [products,setProducts]=useState<any[]>([]); const [query,setQuery]=useState(""); const [category,setCategory]=useState("All"); const [menu,setMenu]=useState(false);
 useEffect(()=>{fetch(API+"/api/marketplace/products").then(r=>r.json()).then(d=>setProducts(d.products||[])).catch(()=>setProducts([]))},[]);
 const productCategories=useMemo(()=>["All",...Array.from(new Set(products.map(p=>p.category)))],[products]);\n const visible=products.filter(p=>(category==="All"||p.category===category)&&p.name.toLowerCase().includes(query.toLowerCase()));
 const selectedId=typeof window!=="undefined"?new URLSearchParams(window.location.search).get("product"):null;
 return <main className="market">
  <div className="marketTopbar">Quality products · Trusted services · LUMIA Marketplace</div><header className="marketHeader"><a className="marketBrand" href="/">LUMIA <span>MARKET</span></a><button className="marketMenu" onClick={()=>setMenu(!menu)}>{menu?"Close":"Menu"}</button><nav className={menu?"navOpen":""}><a href="#products">Products</a><a href="#services">Services</a><a href="/portal">Portal</a></nav><button className="cart"><ShoppingCart size={18}/> Cart</button></header>
  <section className="marketHero"><div><p className="eyebrow">LUMIA SERVICES PROVIDER</p><h1>Everything you need, in one trusted marketplace.</h1><p>Shop products and request professional digital services through the LUMIA ecosystem.</p><a href="#products" className="shopBtn">Explore products <ArrowRight size={18}/></a></div><div className="heroPhoto"><img src="https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1200&q=85" alt="Shopping marketplace"/></div></section>
  <section className="categorySection"><p className="eyebrow">DISCOVER MORE</p><h2>Shop by category</h2><div className="categoryGrid"><button className={category==="All"?"cat activeCat":"cat"} onClick={()=>setCategory("All")}>All products</button>{productCategories.filter((x:any)=>x!=="All").map((name:any)=>{const found=categories.find((x:any)=>x[0]===name);const Icon=found?found[1]:ShoppingCart;return <button key={name} className={category===name?"cat activeCat":"cat"} onClick={()=>setCategory(name)}><Icon size={23}/><span>{name}</span></button>})}</div><div style={{display:"none"}}>{categories.map(([name,Icon]:any)=><button key={name} className={category===name?"cat activeCat":"cat"} onClick={()=>setCategory(name)}><Icon size={23}/><span>{name}</span></button>)}</div></section>
  <section id="products" className="productsSection"><div className="sectionHead"><div><p className="eyebrow">REAL PRODUCTS</p><h2>Featured marketplace</h2></div><div className="searchBox"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products..."/></div></div><div className="productGrid">{visible.map(p=><article className={String(p.id)===selectedId?"productCard selectedProduct":"productCard"} key={p.id}><div className="productImageWrap"><img src={p.image_url||"https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=900&q=80"} alt={p.name}/>{String(p.id)===selectedId&&<b className="selectedBadge">Selected for you</b>}</div><div className="productInfo"><span>{p.category}</span><h3>{p.name}</h3><p>{p.description}</p><strong>{Number(p.price)>0?Number(p.price).toLocaleString()+" "+p.currency:"Request a quote"}</strong><button onClick={()=>alert("Order request: "+p.name+". Payment and confirmation can be completed through the LUMIA team.")}>View product & buy <ArrowRight size={16}/></button></div></article>)}</div></section>
  <section id="services" className="services"><p className="eyebrow">PROFESSIONAL SERVICES</p><h2>Build your next digital project with LUMIA</h2><div><article><Globe size={28}/><h3>Websites</h3><p>Professional business websites and web applications.</p></article><article><Smartphone size={28}/><h3>Mobile Apps</h3><p>Modern Android and mobile applications.</p></article><article><Wrench size={28}/><h3>Custom Solutions</h3><p>Technology solutions for your business.</p></article></div></section>
  <footer>© 2026 LUMIA Market · Connected to LUMIA AI Portal & Backend</footer>
 </main>
}